[tool.poetry]
name = "mailing-demon"
version = "0.1.0"
description = ""
authors = ["Ñ‚"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
apscheduler = "^3.10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
