# Generated by Django 5.0.2 on 2024-03-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_name',
        ),
        migrations.AddField(
            model_name='clients',
            name='name',
            field=models.CharField(default=None, max_length=80, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
