# Generated by Django 5.0.2 on 2024-03-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='mailings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='mailings.mailings', verbose_name='Рассылка'),
        ),
    ]
