# Generated by Django 5.0.2 on 2024-03-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя рассылки'),
        ),
    ]
