# Generated by Django 5.0.2 on 2024-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(default='Создана', max_length=15, verbose_name='Статус рассылки'),
        ),
    ]
