# Generated by Django 5.0.2 on 2024-04-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
